export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_RECEIVE = 'FETCH_RECEIVE';

export const FETCH_CREATE_REQUEST = 'FETCH_CREATE_REQUEST';
export const FETCH_CREATE_RECEIVE = 'FETCH_CREATE_RECEIVE';
